### ISSUE TITLE
Play Session cookie not deleted on logout when MaxAge is not set

### ISSUE THREAD

**Issue by wandliu** [forcedotcom/stargate#14]
A necessary patch was recently applied to clear the play session cookie upon logout to address the following issue.

https://github.com/playframework/playframework/issues/10122

This patch overwrites the play session cookie set to be discarded immediately. However, in some browsers, the cookie is not immediately discarded and it rather retains a play session cookie with empty value instead.

`PLAY_SESSION=; Path=/; Domain=localhost; Secure; HttpOnly;`

In order to clear the cookie, the `maxAge` property needs to be set to 0 so the cookie is set to expired immediately.  This seems to be a common issue. A related issue has been reported here:

https://github.com/playframework/playframework/issues/7680

Local tests confirms that the play cookie is discarded after the fix

**Comment by realstraw** [comment]
playframework/playframework#7680 seems to be unrelated and has been fixed in 2.6
