### ISSUE TITLE
As a developer, I want to be able to retrieve the stackKey from the session, so that I can use a library to roll features out more easily across apps

### ISSUE THREAD

**Issue by yourdon** [forcedotcom/stargate#16]
Currently, `McSsoController` exposes `mid` and `eid` in the `session`. Having access to these is useful for, among many other things, gating access to new features. Adding the stack to the session too would make it simpler to turn on a feature for many customers at once, because we could reference the stack in a library used by multiple apps.

**Comment by realstraw** [comment]
`postLoginCallback` should allow you do retrieve whatever you need, no?

**Comment by yourdon** [comment]
That's true, but the use case here is actually for library code used by multiple apps. So we would have to override `postLoginCallback` in every app. I'll modify the issue description to make this clearer.

**Comment by realstraw** [comment]
Ok, that library does not have to exist in stargate then. We do not want to build in too much opinion on what should be included in stargate. You can create your own shared library code that overriding that callback and share that among your apps

**Comment by yourdon** [comment]
The library wouldn't be in stargate, just the stack attribute, which the library would then be able to access. Is stack more opinionated than eid/mid?

**Comment by realstraw** [comment]
what's stopping you from having a library which depends on stargate, and overrides `postLoginCallback` to provide stacks and other things you looking for?

**Comment by yourdon** [comment]
It seems like each app can have its own logic that it requires in `postLoginCallback`, so we would end up overriding it n times for n apps.

**Comment by yourdon** [comment]
@realstraw Thoughts on the above?

**Comment by realstraw** [comment]
It's hard to understand this. So each app would need to overwrite that anyway, are you trying to avoid having their own logic to retrieve the detail from `mcSsoDecodedJwt`?

**Comment by yourdon** [comment]
Yes, each app will override it anyway with their own logic. However, this one bit of logic (adding stack) will be common across apps. The aim is to avoid (1) duplicating the stack logic in each app, and/or (2) introducing a new controller that adds stack and then also must execute each app's unique postLogin logic. Does that help clarify? 

I guess I'm also not sure why `stack` is more MC-specific than `mid` or `userId`, both of which seem to be MC-specific per [the documentation here](https://github.com/forcedotcom/stargate/blob/master/stargate-core/app/com/salesforce/mce/stargate/controllers/McSsoController.scala#L96-L97). Is the point that external users of Stargate may have access to `mid` and `userId` but would not necessarily know `stack`?

**Comment by yourdon** [comment]
We will handle this outside of Stargate.
